### ISSUE TITLE
some lovin' for the maintenance page

### ISSUE THREAD

**Issue by sjugge** [Wunderkraut-Benelux/wundertheme#13]
When using Wundertheme and the site is put in maintenance mode, you'll notice that the layout and styling of the maintenance page could use some lovin'.

![](https://cldup.com/cvvZKY8zGr-3000x3000.png)

**Comment by seutje** [comment]
Any suggestions? Perhaps we can make it a bit groovy: http://jsfiddle.net/desandro/Ew6Zt/embedded/result/ :P

**Comment by seutje** [comment]
Or maybe heat things up a bit: http://jsbin.com/fire/7

**Comment by seutje** [comment]
![image](https://cloud.githubusercontent.com/assets/150374/18782110/0cd1eb9c-8185-11e6-87f5-9d800103ea43.png)
