### ISSUE TITLE
Not compatible with npm 5.4.*

### ISSUE THREAD

**Issue by mallezie** [Wunderkraut-Benelux/wundertheme#18]
When installing i get the question to update npm from 5.3.0 to 5.4.2. 
However running npm install with npm 5.4.2 does not work. Reinstalling node with npm 5.3.0 fixes the issue now.

**Comment by seutje** [comment]
Cheers, I'll try to look into this coming Friday.

**Comment by seutje** [comment]
Seems to work for me, on both 8.x and 7.x branches. Please post terminal output if it still occurs.
