### ISSUE TITLE
Remove gulp notify from gulp compile command

### ISSUE THREAD

**Issue by mallezie** [Wunderkraut-Benelux/wundertheme#19]
Ideally (and what i run on gimv now). We run gulp compile on the build server, and don't commit the compiled css files. 
The build server however throws a notice (it works) on the gulp-notify statement, since jenkins cannot notify things. 
My suggestion would be to remove the notify from the gulp compile command (we can keep it on the gulp default command). 

This is from jenkins (gimv dev build for reference)
[14:49:16] gulp-notify: [Gulp notification] Styles task complete
[14:49:16] gulp-notify: [Error in notifier] Error in plugin 'gulp-notify'
Message:
    not found: notify-send
Details:
    code: ENOENT

**Comment by seutje** [comment]
Separated sass and sass-dev: sass-dev runs browsersync and notify, sass does not. Compile task uses sass, serve task uses sass-dev.
